### PR TITLE
Add multicolor MD icons for issue states

### PR DESCRIPTION
**Pull request by st161848**
For use in the frontend. All icons contain a base icon that fits in a 24×24 frame and are 32×32 to fit the additional decorations.

preview on light and dark backgrounds

### CODE REVIEW

**Review by spethso — APPROVED** [review]
Only the red arrow for the red icons is hard to recognize

**Comment by st161848** [comment]
Colors are definitely up for debate; it could go more pink or more orange (or something completely different)

more pink
more orange

**Review by nk-coding — APPROVED** [review]
I personally would prefer the orange arrow version

**Comment by nk-coding** [comment]
imho ready to merge

**Pull request merged**
